# Generated by Django 4.2.1 on 2024-02-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnderPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Подпункт меню',
                'verbose_name_plural': 'Подпункты меню',
            },
        ),
        migrations.AddField(
            model_name='menupoint',
            name='underpoint',
            field=models.ManyToManyField(default='', to='menu.underpoint'),
        ),
    ]
